apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: event-listener
spec:
  serviceAccountName: service-account
  triggers:
  - bindings:
    - name: trigger-binding
    template:
      name: trigger-template
