apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: application-pipeline
spec:
  resources:
    - name: git-source
      type: git
  params:
    - name: pathToContext
      description: The path to the build context, used by Kaniko - within the workspace
      default: .
    - name: pathToYamlFile
      description: The path to the yaml file to deploy within the git source
      default: config.yaml
    - name: imageUrl
      description: Url of image repository
      default: deploy_target
    - name: imageTag
      description: Tag to apply to the built image
      default: latest
  tasks:
  - name: build-image-from-source
    taskRef:
      name: build-image-from-source
    params:
    resources:
      inputs:
        - name: git-source
          resource: git
