apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: trigger-binding
spec:
  params:
  - name: git-repo-url
    value: $(event.repository.url)
  - name: git-branch
    value: $(event.ref)
  - name: git-revision
    value: $(event.head_commit.id)
